### ISSUE TITLE
error: failed to compile cargo-udeps v0.1.41

### ISSUE THREAD

**Issue by x011** [est31/cargo-udeps#183] opened 2023-07-23 00:38 UTC
I'm unable to run Owner avatar [archive.observer](https://github.com/raffomania/archive.observer) due to an error on `just init` caused by error: `failed to compile cargo-udeps v0.1.41` :

```
Caused by:
  process didn't exit successfully: `/root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/bin/rustc --crate-name cargo --edition=2021 /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/cargo-0.72.1/src/cargo/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts,future-incompat --diagnostic-width=129 --crate-type lib --emit=dep-info,metadata,link -C opt-level=3 -C panic=abort -C linker-plugin-lto -C codegen-units=1 -C metadata=dfeab6db10d997c0 -C extra-filename=-dfeab6db10d997c0 --out-dir /tmp/cargo-installgRKFmE/release/deps -C strip=symbols -L dependency=/tmp/cargo-installgRKFmE/release/deps --extern anyhow=/tmp/cargo-installgRKFmE/release/deps/libanyhow-2056c4f95393e774.rmeta --extern base64=/tmp/cargo-installgRKFmE/release/deps/libbase64-6e993344c7fb3c2e.rmeta --extern bytesize=/tmp/cargo-installgRKFmE/release/deps/libbytesize-b9df4588b8b14535.rmeta --extern cargo_platform=/tmp/cargo-installgRKFmE/release/deps/libcargo_platform-309ce25f90eace2f.rmeta --extern cargo_util=/tmp/cargo-installgRKFmE/release/deps/libcargo_util-7eef08127841f3f4.rmeta --extern clap=/tmp/cargo-installgRKFmE/release/deps/libclap-006201a193f6b03f.rmeta --extern crates_io=/tmp/cargo-installgRKFmE/release/deps/libcrates_io-d241db66d213ce4e.rmeta --extern curl=/tmp/cargo-installgRKFmE/release/deps/libcurl-1e7ef6ecfc93b7e0.rmeta --extern curl_sys=/tmp/cargo-installgRKFmE/release/deps/libcurl_sys-4c24eb29aa172b4d.rmeta --extern env_logger=/tmp/cargo-installgRKFmE/release/deps/libenv_logger-42000e2092e025e4.rmeta --extern filetime=/tmp/cargo-installgRKFmE/release/deps/libfiletime-61804329a9e97702.rmeta --extern flate2=/tmp/cargo-installgRKFmE/release/deps/libflate2-25bca03e9dc0cd6c.rmeta --extern git2=/tmp/cargo-installgRKFmE/release/deps/libgit2-9eaac4095bd48ee3.rmeta --extern git2_curl=/tmp/cargo-installgRKFmE/release/deps/libgit2_curl-02c6a0388e1d2fa1.rmeta --extern gix=/tmp/cargo-installgRKFmE/release/deps/libgix-8da0f8b846907f9a.rmeta --extern gix_features_for_configuration_only=/tmp/cargo-installgRKFmE/release/deps/libgix_features-100b8dcb6040bcd8.rmeta --extern glob=/tmp/cargo-installgRKFmE/release/deps/libglob-dd2514d9866f2576.rmeta --extern hex=/tmp/cargo-installgRKFmE/release/deps/libhex-1539682706018fb0.rmeta --extern hmac=/tmp/cargo-installgRKFmE/release/deps/libhmac-8226a689ee63a3d6.rmeta --extern home=/tmp/cargo-installgRKFmE/release/deps/libhome-2cb1307591cede11.rmeta --extern http_auth=/tmp/cargo-installgRKFmE/release/deps/libhttp_auth-175d46924445f298.rmeta --extern humantime=/tmp/cargo-installgRKFmE/release/deps/libhumantime-6c514dfff03bfe92.rmeta --extern ignore=/tmp/cargo-installgRKFmE/release/deps/libignore-3b8081b2281853b8.rmeta --extern im_rc=/tmp/cargo-installgRKFmE/release/deps/libim_rc-c81beff7cc42984f.rmeta --extern indexmap=/tmp/cargo-installgRKFmE/release/deps/libindexmap-7a94f9c372418038.rmeta --extern is_terminal=/tmp/cargo-installgRKFmE/release/deps/libis_terminal-f540cb965d25c2af.rmeta --extern itertools=/tmp/cargo-installgRKFmE/release/deps/libitertools-6c7e5c3cee6dd23e.rmeta --extern jobserver=/tmp/cargo-installgRKFmE/release/deps/libjobserver-9594232bdcd4bbad.rmeta --extern lazy_static=/tmp/cargo-installgRKFmE/release/deps/liblazy_static-a8ed0d36d7a69372.rmeta --extern lazycell=/tmp/cargo-installgRKFmE/release/deps/liblazycell-2cfb84c64a2aa95e.rmeta --extern libc=/tmp/cargo-installgRKFmE/release/deps/liblibc-30a20c12bf1dbc3a.rmeta --extern libgit2_sys=/tmp/cargo-installgRKFmE/release/deps/liblibgit2_sys-1e5b9056de9a8565.rmeta --extern log=/tmp/cargo-installgRKFmE/release/deps/liblog-6fd0f07a4ce8d66d.rmeta --extern memchr=/tmp/cargo-installgRKFmE/release/deps/libmemchr-81fcabffbfbddc00.rmeta --extern opener=/tmp/cargo-installgRKFmE/release/deps/libopener-77bad5fbf3f2e49c.rmeta --extern os_info=/tmp/cargo-installgRKFmE/release/deps/libos_info-6badf139eae29c7e.rmeta --extern pasetors=/tmp/cargo-installgRKFmE/release/deps/libpasetors-61ae8bc465951be0.rmeta --extern pathdiff=/tmp/cargo-installgRKFmE/release/deps/libpathdiff-1716a3abe30e85b4.rmeta --extern rand=/tmp/cargo-installgRKFmE/release/deps/librand-67dccd08add74458.rmeta --extern rustfix=/tmp/cargo-installgRKFmE/release/deps/librustfix-c6b1e468025d1e4a.rmeta --extern semver=/tmp/cargo-installgRKFmE/release/deps/libsemver-dd6496872344f289.rmeta --extern serde=/tmp/cargo-installgRKFmE/release/deps/libserde-baf407a4de6be2df.rmeta --extern serde_value=/tmp/cargo-installgRKFmE/release/deps/libserde_value-5660db7ad0928eac.rmeta --extern serde_ignored=/tmp/cargo-installgRKFmE/release/deps/libserde_ignored-468f776cb9b54ca0.rmeta --extern serde_json=/tmp/cargo-installgRKFmE/release/deps/libserde_json-7861a60f4d0f2bb3.rmeta --extern sha1=/tmp/cargo-installgRKFmE/release/deps/libsha1-c6fc1905558476e2.rmeta --extern shell_escape=/tmp/cargo-installgRKFmE/release/deps/libshell_escape-b9f70fa7b4ea5199.rmeta --extern strip_ansi_escapes=/tmp/cargo-installgRKFmE/release/deps/libstrip_ansi_escapes-0a81f28495a2615b.rmeta --extern tar=/tmp/cargo-installgRKFmE/release/deps/libtar-ebea5366f05a6cf2.rmeta --extern tempfile=/tmp/cargo-installgRKFmE/release/deps/libtempfile-9f6b3dee7a8bb5a8.rmeta --extern termcolor=/tmp/cargo-installgRKFmE/release/deps/libtermcolor-c80389f643e59105.rmeta --extern time=/tmp/cargo-installgRKFmE/release/deps/libtime-517b20f827cabbcc.rmeta --extern toml=/tmp/cargo-installgRKFmE/release/deps/libtoml-7966a519bf700df6.rmeta --extern toml_edit=/tmp/cargo-installgRKFmE/release/deps/libtoml_edit-c8c07ce0bbc1f572.rmeta --extern unicode_width=/tmp/cargo-installgRKFmE/release/deps/libunicode_width-13f2590755c321ef.rmeta --extern unicode_xid=/tmp/cargo-installgRKFmE/release/deps/libunicode_xid-01ff37d6de449460.rmeta --extern url=/tmp/cargo-installgRKFmE/release/deps/liburl-1a1d8c9ea33ead2e.rmeta --extern walkdir=/tmp/cargo-installgRKFmE/release/deps/libwalkdir-429d66fadf848984.rmeta --cap-lints allow -L native=/tmp/cargo-installgRKFmE/release/build/curl-sys-ccd9b0e75736c967/out/build -L native=/tmp/cargo-installgRKFmE/release/build/libnghttp2-sys-f33a7877b9213910/out/i/lib -L native=/tmp/cargo-installgRKFmE/release/build/libgit2-sys-63cf82edb560503e/out/build -L native=/tmp/cargo-installgRKFmE/release/build/libssh2-sys-58b6daf96b151cac/out/build` (signal: 9, SIGKILL: kill)
error: failed to compile `cargo-udeps v0.1.41`, intermediate artifacts can be found at `/tmp/cargo-installgRKFmE`
error: Recipe `init` failed on line 101 with exit code 101
```
any idea how to solve this?

**Comment by est31** [comment] 2023-07-23 00:41
@x011 how many cores does your computer have and how much RAM do you have? This looks a lot like an out of memory condition. You could try [compiling with one core instead](https://stackoverflow.com/questions/69100035/how-do-i-set-the-number-of-default-parallel-jobs-j-4-for-cargo).

**Comment by est31** [comment] 2023-08-25 18:31
I suppose the issue is resolved now, closing.

**Closed by est31** 2023-08-25 18:31 UTC
