### ISSUE TITLE
Fix nightly compilation error

### ISSUE THREAD

**Issue by alice-i-cecile** [est31/cargo-udeps#125] opened 2022-06-30 18:25 UTC
This crate no longer compiles under the latest nightly.

We've had to disable this in our CI, tracked here: https://github.com/bevyengine/bevy/issues/5155

**Comment by alice-i-cecile** [comment] 2022-06-30 18:37
My apologies; we appear to be running this on nightly. The timing was just a coincidence :)

**Comment by est31** [comment] 2022-06-30 22:16
Can you tell more about the build error (error message, nightly version, platform, etc)? I have tried to compile it locally on linux with `1.64.0-nightly (ddcbba036 2022-06-29)` and it worked without issues.

**Comment by alice-i-cecile** [comment] 2022-07-01 00:04
@mockersf and @cart ran into this in our CI: 

> no method named `iter` found for opaque type `impl Iterator<Item = &OsString>` in the current scope

I can't track down the failing CI run right now; do either of you have a link to the failing CI run that prompted this?

**Comment by ZaneEme** [comment] 2022-07-01 03:17
Currently running into the same issue and getting the following errors:

error[E0599]: no method named `iter` found for opaque type `impl Iterator<Item = &OsString>` in the current scope
  --> /home/zemerick/.cargo/registry/src/github.com-1ecc6299db9ec823/cargo-0.62.0/src/cargo/core/compiler/build_plan.rs:81:35
   |
81 |         for arg in cmd.get_args().iter() {
   |                                   ^^^^ method not found in `impl Iterator<Item = &OsString>`

error[E0599]: no method named `iter` found for opaque type `impl Iterator<Item = &OsString>` in the current scope
   --> /home/zemerick/.cargo/registry/src/github.com-1ecc6299db9ec823/cargo-0.62.0/src/cargo/core/compiler/mod.rs:757:24
    |
757 |     rustdoc.get_args().iter().any(|flag| {
    |                        ^^^^ method not found in `impl Iterator<Item = &OsString>`

error[E0599]: no method named `hash` found for opaque type `impl Iterator<Item = &OsString>` in the current scope
   --> /home/zemerick/.cargo/registry/src/github.com-1ecc6299db9ec823/cargo-0.62.0/src/cargo/util/rustc.rs:354:20
    |
354 |     cmd.get_args().hash(&mut hasher);
    |                    ^^^^ method not found in `impl Iterator<Item = &OsString>`



When running `cargo install cargo-udeps` using both the stable `rustc 1.62.0 (a8314ef7d 2022-06-27)` and the nightly `rustc 1.64.0-nightly (7425fb293 2022-06-30)` on Ubuntu 22.04.

Hopefully this can be of some help, just let me know if any more information is needed.

**Comment by qryxip** [comment] 2022-07-01 07:29
This problem seems to be due to an unexpected breaking change in [cargo-util](https://docs.rs/crate/cargo-util).

https://docs.rs/cargo-util/0.1.2/cargo_util/struct.ProcessBuilder.html#method.get_args
↓
https://docs.rs/cargo-util/0.1.3/cargo_util/struct.ProcessBuilder.html#method.get_args

I think this problem is already resolved because cargo-util v0.1.3 was yanked and the v0.2.0 was released.

https://crates.io/crates/cargo-util/versions

**Comment by est31** [comment] 2022-07-01 21:28
So another instance of https://github.com/rust-lang/cargo/issues/7169#issuecomment-614343884 then? It checks out then why it didn't break for me because I tried building from my local git clone which uses the checked in lockfile. Closing as not a bug in cargo-udeps.

**Closed by est31** 2022-07-01 21:28 UTC
