### ISSUE TITLE
Getting this uncought exception when attempting to test on [arbiter](https://github.com/primitivefinance/arbiter/issues/608)

### ISSUE THREAD

**Issue by 0xJepsen** [est31/cargo-udeps#218] opened 2023-10-16 21:28 UTC
I would like to add this to our CI/CD on arbiter but am getting this uncaught exception when running locally. Any idea what i may be doing wrong?
```
cargo +nightly udeps                                                 ABRT ✘ │ 1  │ at 15:25:14 
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[__NSCFString stringByStandardizingPath]: unrecognized selector sent to instance 0x14960a0f0'
*** First throw call stack:
(
        0   CoreFoundation                      0x00000001877cc8c0 __exceptionPreprocess + 176
        1   libobjc.A.dylib                     0x00000001872c5eb4 objc_exception_throw + 60
        2   CoreFoundation                      0x000000018787e3dc -[NSObject(NSObject) __retain_OA] + 0
        3   CoreFoundation                      0x00000001877369e4 ___forwarding___ + 1572
        4   CoreFoundation                      0x0000000187736300 _CF_forwarding_prep_0 + 96
        5   Foundation                          0x000000018880b4f0 -[NSProcessInfo arguments] + 188
        6   CoreFoundation                      0x0000000187847ff8 __getDefaultArguments_block_invoke + 96
        7   libdispatch.dylib                   0x00000001874cd910 _dispatch_client_callout + 20
        8   libdispatch.dylib                   0x00000001874cf14c _dispatch_once_callout + 32
        9   CoreFoundation                      0x0000000187847994 _addBackstopValuesForIdentifierAndSource + 640
        10  CoreFoundation                      0x0000000187702254 __81-[_CFXPreferences(SourceAdditions) withNamedVolatileSourceForIdentifier:perform:]_block_invoke + 144
        11  CoreFoundation                      0x000000018784763c -[_CFXPreferences withNamedVolatileSourceForIdentifier:perform:] + 272
        12  CoreFoundation                      0x00000001877085c4 -[CFPrefsSearchListSource addNamedVolatileSourceForIdentifier:] + 136
        13  CoreFoundation                      0x00000001878868bc __108-[_CFXPreferences(SearchListAdditions) withSearchListForIdentifier:container:cloudConfigurationURL:perform:]_block_invoke.155 + 296
        14  CoreFoundation                      0x0000000187886564 -[_CFXPreferences withSearchLists:] + 84
        15  CoreFoundation                      0x0000000187703b18 __108-[_CFXPreferences(SearchListAdditions) withSearchListForIdentifier:container:cloudConfigurationURL:perform:]_block_invoke + 300
        16  CoreFoundation                      0x0000000187886710 -[_CFXPreferences withSearchListForIdentifier:container:cloudConfigurationURL:perform:] + 384
        17  CoreFoundation                      0x0000000187703440 -[_CFXPreferences copyAppValueForKey:identifier:container:configurationURL:] + 156
        18  CoreFoundation                      0x0000000187703368 _CFPreferencesCopyAppValueWithContainerAndConfiguration + 112
        19  SystemConfiguration                 0x0000000188493478 SCDynamicStoreCopyProxiesWithOptions + 180
        20  cargo-udeps                         0x0000000104969abc cargo-udeps + 7707324
        21  cargo-udeps                         0x0000000104958358 cargo-udeps + 7635800
        22  cargo-udeps                         0x00000001045e4898 cargo-udeps + 4016280
        23  cargo-udeps                         0x0000000104a08fe8 cargo-udeps + 8359912
        24  cargo-udeps                         0x00000001045e4808 cargo-udeps + 4016136
        25  dyld                                0x000000018731d5c8 ___ZZNK5dyld46Loader25findAndRunAllInitializersERNS_12RuntimeStateEENK3$_0clEv_block_invoke + 168
        26  dyld                                0x0000000187362920 ___ZNK5dyld313MachOAnalyzer18forEachInitializerER11DiagnosticsRKNS0_15VMAddrConverterEU13block_pointerFvjEPKv_block_invoke.209 + 340
        27  dyld                                0x0000000187355c60 ___ZNK5dyld39MachOFile14forEachSectionEU13block_pointerFvRKNS0_11SectionInfoEbRbE_block_invoke + 496
        28  dyld                                0x00000001872fd2fc _ZNK5dyld39MachOFile18forEachLoadCommandER11DiagnosticsU13block_pointerFvPK12load_commandRbE + 300
        29  dyld                                0x0000000187354c98 _ZNK5dyld39MachOFile14forEachSectionEU13block_pointerFvRKNS0_11SectionInfoEbRbE + 192
        30  dyld                                0x0000000187362434 _ZNK5dyld313MachOAnalyzer18forEachInitializerER11DiagnosticsRKNS0_15VMAddrConverterEU13block_pointerFvjEPKv + 516
        31  dyld                                0x0000000187319798 _ZNK5dyld46Loader25findAndRunAllInitializersERNS_12RuntimeStateE + 448
        32  dyld                                0x000000018731fb14 _ZNK5dyld416JustInTimeLoader15runInitializersERNS_12RuntimeStateE + 36
        33  dyld                                0x0000000187319b4c _ZNK5dyld46Loader23runInitializersBottomUpERNS_12RuntimeStateERN5dyld35ArrayIPKS0_EE + 220
        34  dyld                                0x000000018731d654 _ZZNK5dyld46Loader38runInitializersBottomUpPlusUpwardLinksERNS_12RuntimeStateEENK3$_1clEv + 112
        35  dyld                                0x0000000187319ccc _ZNK5dyld46Loader38runInitializersBottomUpPlusUpwardLinksERNS_12RuntimeStateE + 304
        36  dyld                                0x000000018733ead4 _ZN5dyld44APIs25runAllInitializersForMainEv + 464
        37  dyld                                0x0000000187301f34 _ZN5dyld4L7prepareERNS_4APIsEPKN5dyld313MachOAnalyzerE + 3192
        38  dyld                                0x0000000187300f44 start + 1948
)
libc++abi: terminating due to uncaught exception of type NSException
zsh: abort      cargo +nightly udeps
```

**Comment by est31** [comment] 2023-10-16 22:35
This is a dupe of #213, and not really a cargo-udeps issue

**Closed by est31** 2023-10-16 22:35 UTC
