### ISSUE TITLE
json output: `unused_deps` may be non-empty even if all dependencies are used

### ISSUE THREAD

**Issue by nagisa** [est31/cargo-udeps#78] opened 2020-10-30 13:07 UTC
```json
{"success":true,"unused_deps":{"some crate":{"manifest_path":"/some/location","normal":[],"development":[],"build":[]}},"note":null}
```

is what I see when I build a workspace with many crates. The `unused_deps` map gets populated with further crates if and when they contain unused crates.

I think it might be because the `some_crate` is the only crate that has `cargo-udeps.ignore` specified in it.

**Comment by est31** [comment] 2020-10-30 14:57
Might be one of the known false positives? The cli version shows a warning that this is possible.

**Comment by nagisa** [comment] 2020-10-30 16:26
Note that there are no reported unused dependencies, all of the `normal`, `development` and `build` arrays for that crate are empty. Furthermore json contains both `success: true` and udeps' exit code is 0.

**Comment by nagisa** [comment] 2020-10-30 16:26
All in all it is fairly low prio to fix, just something I noticed and found weird.

**Comment by qryxip** [comment] 2020-10-31 08:58
I've found the cause. It checks if the dependency is `ignore`d after inserting `([], [], [])`. I don't remember the reason why we pass `([], [], [])`.

https://github.com/est31/cargo-udeps/blob/13ea33051882cdd5116a56410453b9deee3b6c89/src/lib.rs#L473-L485
https://github.com/est31/cargo-udeps/blob/13ea33051882cdd5116a56410453b9deee3b6c89/src/lib.rs#L489-L494

**Comment by qryxip** [comment] 2020-10-31 09:16
I've just noticed the `--output json` option is not documented at all. Maybe we should write some descriptions.

**Comment by qryxip** [comment] 2020-10-31 09:27
Either way this issue is actually weird and should be fixed.

**Closed** 2020-10-31 10:12 UTC
