### ISSUE TITLE
use nightly on install also?

### ISSUE THREAD

**Issue by sampaioletti** [est31/cargo-udeps#94] opened 2021-05-11 14:10 UTC
Could be just me (:

but i had to use nightly on my install also.

This fails to build
```sh
cargo install cargo-udeps --locked
```
No issues
```sh
cargo +nightly install cargo-udeps --locked
```

**Comment by qryxip** [comment] 2021-05-11 14:23
I could not reproduce with Rust 1.52.1. Could you share the error message?

```console
❯ rustc --version
rustc 1.52.1 (9bc8c42bb 2021-05-09)
❯ cargo install cargo-udeps --locked
    Updating crates.io index
  Downloaded cargo-udeps v0.1.21
  Downloaded 1 crate (30.3 KB) in 0.82s
  Installing cargo-udeps v0.1.21
  Downloaded curl v0.4.36
  Downloaded sized-chunks v0.6.5
  Downloaded cargo v0.53.0
  Downloaded libgit2-sys v0.12.19+1.1.0
  Downloaded curl-sys v0.4.42+curl-7.76.0
  Downloaded git2 v0.13.18
  Downloaded 6 crates (6.1 MB) in 2.01s (largest was `curl-sys` at 2.9 MB)
   Compiling libc v0.2.94
   ⋮
   Compiling cargo-udeps v0.1.21
    Finished release [optimized] target(s) in 2m 59s
   Replacing /home/ryo/.cargo/bin/cargo-udeps                                                                                       Replaced package `cargo-udeps v0.1.15 (/home/ryo/src/github.com/est31/cargo-udeps)` with `cargo-udeps v0.1.21` (executable `cargo-udeps`)
```

**Comment by est31** [comment] 2021-07-02 08:10
Closing because there was no reaction. Please comment if you still encounter this, sharing the error message.

**Closed by est31** 2021-07-02 08:10 UTC

**Comment by rwestphal** [comment] 2022-01-08 14:24
I was also getting this error and installing `libcurl4-openssl-dev` (Debian package) fixed the problem for me.
