### ISSUE TITLE
unused dependency not found by cargo-udeps (false negative)

### ISSUE THREAD

**Issue by bnjbvr** [est31/cargo-udeps#105] opened 2021-11-02 16:15 UTC
Hi! Thanks for making this great tool, first. It's been quite useful in the past.

I've noticed one pattern where it seems that `cargo-udeps` can't find an unused dependency, and I've made a small repo with a repro in there: https://github.com/bnjbvr/udeps-false-negative

The same kind of issue can happen with dependencies transitively used within a workspace, that are not used by some crates up the tree, but are used by leaves.

In general, removing unused dependencies can have two benefits: not downloading and compiling actually unused dependencies, but also move the order of compiling crates in the crate compilation graph, which can result in interesting speedups because concurrent compilation. `cargo-udeps` can identify the former case pretty well, but I think there are missed opportunities when it comes to the latter case. In the above example, noticing that `lib1` isn't used by the binary would make it possible to compile it right after `lib2` has been analyzed, instead of after both `lib1` and `lib2` have been analyzed.

**Comment by est31** [comment] 2021-11-02 17:00
Thanks for filing! This is a dupe of #84, closing.

**Closed by est31** 2021-11-02 17:00 UTC
